# Generated by Django 5.0.6 on 2024-07-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='brith_date',
            new_name='birth_date',
        ),
    ]
