# Generated by Django 5.0.6 on 2024-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_bankrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='account_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
