# Generated by Django 5.0.6 on 2024-07-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_userbankaccount_account_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
    ]
